events { worker_connections 1024; }

http {
    resolver 127.0.0.11 valid=5s;

    # Automatically redirect any HTTP (Port 80) traffic to secure HTTPS
    server {
        listen 80;
        server_name lizardkinglk.xyz www.lizardkinglk.xyz;
        return 301 https://$host$request_uri;
    }

    # Secure HTTPS Server Block (Port 443)
    server {
        listen 443 ssl;
        server_name lizardkinglk.xyz www.lizardkinglk.xyz;

        # Link to the generated certificates
        ssl_certificate /etc/letsencrypt/live/lizardkinglk.xyz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/lizardkinglk.xyz/privkey.pem;

        location /api/azure-alerts {
            set $backend http://dotnet_api:80;

            proxy_pass $backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            set $dashboard http://grafana:3000;
            proxy_pass $dashboard;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}