// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AMonitor.API.Data.Compiled
{
    public partial class ApplicationDbContextModel
    {
        private ApplicationDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("afdb164f-9ff7-46f8-91fd-c58478d5645d"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var azureCommonAlertPayload = AzureCommonAlertPayloadEntityType.Create(this);

            AzureCommonAlertPayloadEntityType.CreateAnnotations(azureCommonAlertPayload);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.9");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
