// <auto-generated />
using AMonitor.API.Data;
using AMonitor.API.Data.Compiled;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ApplicationDbContext), typeof(ApplicationDbContextModel))]
