name: Secure Production CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Executing Remote SSH Commands to Deploy
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: |
            echo "Checking if application directory exists..."
            if [ ! -d "$HOME/amonitor-app" ]; then
            echo "Fresh VM detected! Cloning repository for the first time..."
            git clone ${{ secrets.REPO_URL }} $HOME/amonitor-app
            fi

            cd $HOME/amonitor-app

            echo "Enforcing HTTPS format for Git remote origin..."
            git remote set-url origin ${{ secrets.REPO_URL }}

            echo "Pulling latest code updates..."
            git pull origin main

            echo "Safely stopping and cleaning up existing container stacks..."
            docker compose -f docker-compose.yml -f docker-compose.prod.yml down || true

            export DB_CONNECTION_STRING="${{ secrets.DB_CONNECTION_STRING }}"
            export QUEUE_CONNECTION_STRING="${{ secrets.QUEUE_CONNECTION_STRING }}"
            export QUEUE_NAME="${{ secrets.QUEUE_NAME }}"

            echo "Recompiling source code and starting Production environment..."
            timeout 30s docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build || true

            echo "Backgrounding containers for permanent cloud execution..."
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

            echo "Deployment loop complete!"
